### ISSUE TITLE
Error: Summary: NoSuchElement

### ISSUE THREAD

**Issue by urskalbitzer** [prioritizr/wdpar#11]
Hi,
The package looks very interesting and tried to use it today for the first time. Unfortunately, I ran into a problem when I tried to fetch data.

After getting the error message (see below), I installed the most recent version of wdpar from github, and also updated all other packages, but I still get the same erro.

I'm running RStudio on MacOS 10.14.4.

It would be great if I could use the package on my computer.

Thanks a lot,
Urs

``` r
# load packages

library(wdpar)
library(dplyr)

# download protected area data for Malta
mlt_raw_pa_data <- wdpa_fetch("Malta", wait = TRUE)
#> Error:    Summary: NoSuchElement
#>       Detail: An element could not be located on the page using the given search parameters.
#>       class: org.openqa.selenium.NoSuchElementException
#>   Further Details: run errorDetails method
```

<sup>Created on 2019-04-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jeffreyhanson** [comment]
Thank you very much for reporting this - it looks like protected planet has updated their website and so this package needs to be updated as well to download the protected area data. I'll see if I can sort this out over the next few days. In the meantime though, you can manually download the protected area data of your choice and import it into R using `sf::read_sf` and then use `wdpar::wdpa_clean` to clean the data.

**Comment by urskalbitzer** [comment]
Thanks a lot for the quick response.
I will download the data from the web page and import it with sf::st_read.

**Comment by jeffreyhanson** [comment]
@urskalbitzer, I've just pushed a new version to GitHub that fixes the problem on my computer. Could you please try installing this developmental version (see README for instructions), and try rerunning the example on your computer?

**Comment by urskalbitzer** [comment]
@jeffreyhanson, thanks for this very quick fix. I've just tried it with the new version from GitHub and it works perfectly.

**Comment by jeffreyhanson** [comment]
Awesome - thank you very much! I'll bump the version and send it to CRAN.
