### ISSUE TITLE
typology evaluation errors in wdpa_clean

### ISSUE THREAD

**Issue by JonasGeschke** [prioritizr/wdpar#20]
in addition to #19, I came across the following error in the "DNK" (Denmark) subset:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 1029038.938 6096087.5300000003.

**Comment by JonasGeschke** [comment]
same in the "GRC" (Greece) subset:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 2004406 4598038.

**Comment by JonasGeschke** [comment]
(just noting it here to have a collection where errors pop up. the more often they appear, the more general the problem probably is ...)

**Comment by JonasGeschke** [comment]
same in the "BGR" (Bulgaria) subset:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 2624909 4999187.7525391364.

**Comment by JonasGeschke** [comment]
same **but different** in the "AUT" (Austria) subset:

> Error in CPL_geos_op2(op, st_geometry(x), st_geometry(y)) : 
  Evaluation error: TopologyException: no outgoing dirEdge found at 1243901 5365689.0999999996.

**Comment by JonasGeschke** [comment]
just see similar errors are dealt with in #13. are the code fixes already on CRAN?

**Comment by JonasGeschke** [comment]
error in "BEL" Belgium subset:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 427241 5675070.

**Comment by JonasGeschke** [comment]
error in "BRA" Brazil subset:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at -4449272 -152694.

**Comment by jeffreyhanson** [comment]
Thanks for reporting this - I'll take a look and see what I can do. In the meantime, if you're planning on dissolving all the polygons together or rasterizing the polygons then you can skip this "erasing overlaps" step `erase_overlaps = TRUE`.

**Comment by JonasGeschke** [comment]
Thanks for checking it. Probably the errors are done with the fix in #13, I didnt check this.

**Comment by JonasGeschke** [comment]
another error in "ITA" (Italy):

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 1025649 5066855.

**Comment by JonasGeschke** [comment]
another error in "ESP" (Spain):

> Error in CPL_geos_union(st_geometry(x), by_feature) : 
  Evaluation error: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -517842 4727376.2839926593 at -517842 4727376.2839926593.

**Comment by JonasGeschke** [comment]
another error in "GBR" (United Kingdom):

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at -307405 6250924.

**Comment by JonasGeschke** [comment]
I now re-run cleaning with the development version of `wdpar`. I mark all errors that are resolved with a _thumb-up_ ...

**Comment by JonasGeschke** [comment]
> Thanks for reporting this - I'll take a look and see what I can do. In the meantime, if you're planning on dissolving all the polygons together or rasterizing the polygons then you can skip this "erasing overlaps" step `erase_overlaps = TRUE`.

As a simple feedback question to this point: Sounds like you wouldn't use `wdpa_clean` for dissolving the WDPA. How would you do it?

**Comment by JonasGeschke** [comment]
For now, with use of the development version of `wdpar`, only GRC keeps to result in the error:

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 2624909 4999187.7525391364.

// Germany and US subset still to be done ...

**Comment by JonasGeschke** [comment]
error in "DEU" (Germany":

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at 1273919.4773302849 5975333.6278681727.

**Comment by JonasGeschke** [comment]
also in "USA":

> Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  Evaluation error: TopologyException: side location conflict at -11068713 4016836.

**Comment by jeffreyhanson** [comment]
Hmm, you might need to increase the precision of the geometry calculations for these datasets. Try increasing the `geometry_precision` argument to `1e+6` or `1e+8` in `wdpa_clean`. This makes the geoprocesssing more robust/correct, but increases run time, so finding the right balance can be tricky.

**Comment by jeffreyhanson** [comment]
I've just posted a patch which should make the overlap erasing procedure in `wdpa_clean` more robust, so hopefully this fixes the issues you're experiencing. Could you please try with the latest version?

**Comment by JonasGeschke** [comment]
Great, thanks, I will let you know how it works out.

**Comment by JonasGeschke** [comment]
Working with the development version of `wdpar`, there are currently no typology evaluation errors anymore (even without changing the precision).
