### ISSUE TITLE
wdpa_clean doesnt work offline

### ISSUE THREAD

**Issue by JonasGeschke** [prioritizr/wdpar#21]
Hi, another issue I came across while working on the train: `wdpa_clean` doesnt work offline:

> Error: curl::has_internet() is not TRUE

I guess this is due to the `wdpa_url` and `wdpa_fetch` functions that need internet connection, but `wdpa_clean` shouldnt need to, right?

**Comment by jeffreyhanson** [comment]
Yeah, `wdpa_clean` shouldn't need an internet connection. Thanks for raising this issue - I'll try and fix this sometime this week.

**Comment by jeffreyhanson** [comment]
I've just pushed a fix addressing this issue - thanks again for raising it.
