### ISSUE TITLE
wdpa_fetch error

### ISSUE THREAD

**Issue by IsaakBM** [prioritizr/wdpar#23]
Hi @jeffreyhanson 

I'm just starting to play with this package and I'm getting this error 

`Error: x must be a vector, not a sfc_MULTIPOINT/sfc object`

Not really sure what I'm doing wrong, I just copied the example ` mlt_raw_pa_data <- wdpa_fetch("Malta", wait = TRUE)`

Do you have any hint of what this is about?

Thanks in advance!
Isaac

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for checking our wdpar! I'm sorry, I can't seem to replicate the issue on my computer, could you please post your session information (i.e. `sessionInfo()`)? If you haven't already, could you try  installing the developmental version on GitHub?

Cheers,

Jeff

**Comment by jeffreyhanson** [comment]
Hmm, it looks like the version of sf you have installed is a bit old - could you please try updating it to the latest CRAN version?

**Comment by IsaakBM** [comment]
Yep, that was the problem. Just an FYI, I had to install the dev version of sf to avoid the issue. It's working now. Thanks @jeffreyhanson

**Comment by jeffreyhanson** [comment]
Awesome - glad its working now! I'll close this issue now that it's resolved, and please feel free to open another issue if you encounter any more problems.
