### ISSUE TITLE
lwgeom::st_make_valid --> not exported object from namespace lwgeom

### ISSUE THREAD

**Issue by carbonmetrics** [prioritizr/wdpar#25]
The `wdpa_clean` function calls `lwgeom::st_make_valid` in a few places. This causes an error, because the `lwgeom` package does not have that function. 
I have replaced the calls with `sf::st_make_valid`, but that still returns an error after the function runs.

**Comment by jeffreyhanson** [comment]
Thanks for looking into this. Just to double check, are you using the new version wdpar (1.0.2)? It should have fixed these issue, but I could have missed something?

**Comment by carbonmetrics** [comment]
Thanks for the quick reaction. I am using 1.0.2. - just installed from GitHub and upgraded all required/suggested packages. Same message. 

> > ken_clean=wdpa_clean(ken_pa)
> removing areas that are not implemented: ✓
> removing UNESCO reserves: ✓
> removing points with no reported area: ✓
> Error: 'st_make_valid' is not an exported object from 'namespace:lwgeom'
> > packageVersion("wdpar")
> [1] ‘1.0.2’

**Comment by jeffreyhanson** [comment]
Hmm, I'm having trouble reproducing this error. Could you please run the following code and post the output? 

```
library(wdpar)
x <- wdpa_clean(suppressWarnings(wdpa_fetch("MHL")))
```

Also, could you please print your installed version of the lwgeom package?

**Comment by carbonmetrics** [comment]
It also works for me now! The error was copied/pasted from a vanilla R session after installation / updating ...don't ask. Thanks for your help!

**Comment by jeffreyhanson** [comment]
Ah ok - glad it's working now. I'll close this issue then, but please reopen it if you run into this problem again.
