### ISSUE TITLE
Error when retrieving global WDPA dataset

### ISSUE THREAD

**Issue by Louis-Backstrom** [prioritizr/wdpar#31]
when running the latest dev version of the package, I get an error when trying to download the whole WDPA using the following code:

`wdpa_global <- wdpa_fetch("global", 
                          wait = TRUE,
                          download_dir = "~/Science/Data/GIS/WDPA - World",
                          force_download = TRUE,
                          verbose = TRUE)`

Cannot open layer WDPA_poly_Dec2020
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.

Curiously, however, the file appears to download (in full) into the designated directory (WDPA_Dec2020_Public.gdb.zip, ~1.35 GB) - so it's not a major problem, but figured worth bringing up.

**Comment by jeffreyhanson** [comment]
Hey @Louis-Backstrom, thank you very much for reporting this! I'll have a look later today and see if I can work out what's going wrong.

**Comment by jeffreyhanson** [comment]
Sorry for the delay @Louis-Backstrom, can you please try the GitHub version of wdpar now? It should work with the new version of the WPDA data.

**Comment by Louis-Backstrom** [comment]
All fixed by the looks of it - thanks @jeffreyhanson

**Comment by jeffreyhanson** [comment]
Awesome - great to hear - thanks!
