### ISSUE TITLE
Request to download individual PAs

### ISSUE THREAD

**Issue by Jo-Schie** [prioritizr/wdpar#32]
Hi. Thanks for this helpful package. I'd like to know if there ist the possibility to download individual Protected Areas given the WDPA id or if this query could by implemented. We work with a list of PAs from different countries and downloading all data is lengthy and sometimes unnecessary, especially in automated tasks. Would be nice to hear back from you.

**Comment by jeffreyhanson** [comment]
Thanks for reaching out! Yeah I completely understand that downloading the entire WDPA isn't really helpful/useful for those sorts of tasks. Although this package isn't designed for downloading individual PAs, there do seem to be some other R packages designed specifically for this task (see https://github.com/ljvillanueva/rWDPA, https://github.com/Rekyt/rwdpa). Have you tried those out? Maybe you could develop a workflow to use the rWDPA package to download the PA data/boundaries, and then (if needed?) use this package to clean/prepare the data for subsequent analysis? How does that sound?

**Comment by Jo-Schie** [comment]
Hi jeffrey. The two packages you mentioned are outdated or not maintained. Anyways, my code still does what it should do, with a bit of latency, so it is fine I guess. I will, however, if you do not mind request another feature in a new issue.
