### ISSUE TITLE
Poor internet connection breaks wdpa_fetch

### ISSUE THREAD

**Issue by PhDyellow** [prioritizr/wdpar#39]
I am using version 1.3.1.3.

When I called `aus_mpa <- wdpa_fetch("Australia", wait = TRUE)`, I got the following error:
```
Error: 	 Summary: NoSuchElement
 	 Detail: An element could not be located on the page using the given search parameters.
 	 class: org.openqa.selenium.NoSuchElementException
	 Further Details: run errorDetails method
```

I am aware of #35, so I made sure to use a recent github version of `wdpar`. The issue went away when I switched to a faster, non-mobile, connection. 

Reading around, it seems like PhantomJS doesn't have a good way to know if the page has loaded yet, would it make sense to parameterize the sleep timer in `wdpa_url` instead?

**Comment by PhDyellow** [comment]
I suggest `page_wait`: not too long, and starting with page gives some contrast to the `wait` parameter.

In the end though, I think any of the ideas so far are fine. Thanks for putting together the fix quickly!

**Comment by jeffreyhanson** [comment]
Ok - sounds good! I'll try and get that merged into the main branch tonight.

**Comment by jeffreyhanson** [comment]
I've just merged the PR - so if you install from the main branch, there's the new `page_wait` parameter to control sleep times. Let me know if you run into any issues with it?
