### ISSUE TITLE
I used the newest version of wdpar, still have this "side location conflict"

### ISSUE THREAD

**Issue by sahmoli** [prioritizr/wdpar#48]
Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  :
  Evaluation error: TopologyException: side location conflict at 678942 5359610.1668073526.

What should I do with this?

Thank you so much.

**Comment by jeffreyhanson** [comment]
Hi @sahmoli,

My guess would be that there's a protected area with an invalid geometry that the code for repairing geometries is unable to fix. Could you please put togeather a small reprex to help me debug this? Also, are you processing the data for a specific country?

**Comment by sahmoli** [comment]
I am processing the shapefile of the global protected area downloaded from protectedplanet.org (the May 2022 version). It has three shapefiles in total. I successfully cleaned with erase_overlaps = TRUE of one of them, but the other two shapefiles encountered this error.

**Comment by sahmoli** [comment]
Maybe because the original dataset is too big, it seems like it took reprex() forever to make a reproducible example.

**Comment by jeffreyhanson** [comment]
Yeah, could you please save the R object as an RDS file using `saveRDS` and send that to me? Also, one option could be to try playing around with the parameters used in `wdap_clean()` (e.g., `snap_tolerance` and `geometry_precision`). By increasing them, this will make the geporcessing more robust (but run slower).

**Comment by jeffreyhanson** [comment]
I think we managed to solve this over email, so I'll close this now. Please feel free to re-open if needed?
