### ISSUE TITLE
GEOS version sensitivity

### ISSUE THREAD

**Issue by rsbivand** [prioritizr/wdpar#50]
[00check.log](https://github.com/prioritizr/wdpar/files/9037906/00check.log)
[testthat.Rout.fail.log](https://github.com/prioritizr/wdpar/files/9037910/testthat.Rout.fail.log)

for GEOS 3.11.0 show a failure probably because of fixes in GEOS to the NG topology engine re-ordering the coordinates of the polygon returned by `sf::st_union(x))`:
```
> st_coordinates(st_geometry(y))
        X   Y L1 L2
 [1,]  50  50  1  1
 [2,]   0  50  1  1
 [3,]  75 125  1  1
 [4,]   0 125  1  1
 [5,] 100 250  1  1
 [6,] 200 125  1  1
 [7,] 125 125  1  1
 [8,] 200  50  1  1
 [9,] 150  50  1  1
[10,] 200   0  1  1
[11,]   0   0  1  1
[12,]  50  50  1  1
> st_coordinates(st_geometry(y2))
        X   Y L1 L2
 [1,] 200   0  1  1
 [2,]   0   0  1  1
 [3,]  50  50  1  1
 [4,]   0  50  1  1
 [5,]  75 125  1  1
 [6,]   0 125  1  1
 [7,] 100 250  1  1
 [8,] 200 125  1  1
 [9,] 125 125  1  1
[10,] 200  50  1  1
[11,] 150  50  1  1
[12,] 200   0  1  1
```
Please adapt equality test - perhaps drop or compare areas.

**Comment by jeffreyhanson** [comment]
Hi @rsbivand,

Thank you very much for letting me know. I'll try and fix this as soon as I can. Just so that I'm aware of the timelines, how soon does the fix for wdpar need to be on CRAN?

**Comment by rsbivand** [comment]
Thanks! Timing unpredictable, GEOS 3.11.0 was just released, and CRAN waits for Debian and Fedora packages, so it depends on the upstream package maintainers' urgency or not. I have 3.11.0 installed, so please ping me when you have a fix that needs trying.

**Comment by jeffreyhanson** [comment]
Ok - yeah, that would be extremely helpful, I'll let you know when I've got a (potential) fix ready - thanks!

**Comment by jeffreyhanson** [comment]
@rsbivand, I've just pushed a fix to the `fix-geos` branch. When you get a chance, could you please try it out and see if that fixes it? I've updated the test to use `st_equals()` which returns `TRUE` when comparing the coordinates you posted earlier?

**Comment by rsbivand** [comment]
Logs for `_SP_EVOLUTION_STATUS=2 _R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check wdpar_1.3.2.4.tar.gz` and `_SP_EVOLUTION_STATUS_=2 R CMD build --no-build-vignettes wdpar-fix-geos`:

[00check.log](https://github.com/prioritizr/wdpar/files/9044347/00check.log)

[testthat.Rout.log](https://github.com/prioritizr/wdpar/files/9044346/testthat.Rout.log)

Looks OK! When the evolution process has moved a bit more forward, **sp** will be flipped from evolution status 0 using **rgdal** under the hood to evolution status 2 using sf under the hood, so the environment variable will cease to be needed.

**Comment by jeffreyhanson** [comment]
Awesome! Thank you for checking that. I'll try and submit an update to CRAN sometime today or tomorrow.

**Comment by jeffreyhanson** [comment]
Just to let you know, I submitted the update yesterday and received notification that it's on it's way to CRAN.
