### ISSUE TITLE
wdpa_fetch() no longer works

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/wdpar#63]
The PhantomJS web driver is no longer supported by the RSelenium package, and so this function no longers works. I need to find another package to replace the Rselenium dependency.

**Comment by fBedecarrats** [comment]
Hi, I see that this has already been identified by @Jo-Schie, but I'm affraid that the solution doesn't work on linux: 
```r
remotes::install_github("prioritizr/wdpar", quiet = TRUE, force = TRUE,
                        upgrade = "always")
library(dplyr)
library(wdpar)

# Downloading Protected areas from Madagascar
PA_mada <- wdpa_fetch("Madagascar", wait = TRUE,
                      download_dir = "data_s3/WDPA") %>%
  filter(STATUS != "Proposed") %>%
  filter(DESIG != "Locally Managed Marine Area", DESIG != "Marine Park") 
```
Which returns the following error:
![Screenshot from 2022-10-14 11-37-12](https://user-images.githubusercontent.com/3328347/195815140-ce2b131d-a705-45de-8bc0-4a46eb12c02d.png)

It is running on Ubuntu 20.04, with R 4.2.1

**Comment by jeffreyhanson** [comment]
Thank you very much Hmm, the `webdriver::r

**Comment by fBedecarrats** [comment]
I just tried and it worked indeed!  I agree that a message to the user would be useful to help solve this error. Thanks a lot.

**Comment by jeffreyhanson** [comment]
Ok excellent - thanks! Yeah, I'll update the error message.
