### ISSUE TITLE
Dissolve all MPAs in each country

### ISSUE THREAD

**Issue by fabeit** [prioritizr/wdpar#67]
Thanks a lot for this package, unfortunately I haven't enabled to use it effectively. I'm trying to perform a global analysis and I would need to dissolve all PAs and MPAs for each country. This would mean one polygon for each country, so I can perform spatial analysis by country on a global scale.

Unfortunately when I work with the global data set and follow the provided instructions I get errors about vertices and R freezes. Is there a dissolved global shapefile by country or a way to produce it with this package?

**Comment by fabeit** [comment]
Thanks for the quick reply. Yes I am using that function and it stalls or gives errors. I can try with a larger value but how do I dissolve per country?

**Comment by jeffreyhanson** [comment]
Yeah, you could do something like this (see below). The code assumes that `x` is your cleaned version of the data, and the column `COUNTRY` has the country name for each protected area. I haven't tested this, so it might need some debugging.

```
# load packages
library(wdpar)
library(sf)
library(dplyr)

# dissolve by country
result <-
  x %>%
  split(.$COUNTRY) %>% 
  lapply(function(y) {
    n <- y$COUNTRY[[1]]
    y <- wdpa_dissolve(y)
    y$COUNTRY <- n
    y
  }) %>% 
  bind_rows()
```

**Comment by fabeit** [comment]
Thank you for the suggestion Jeffrey. Unfortunately I run into the same error that I get when I tried to dissolve the global data set such as

Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented = oriented,  : 
  Loop 2 is not valid: Edge 2 crosses edge 4y, I also tried geometry_precision = 1500000000 and I get

Error in wk_handle.wk_wkb(wkb, s2_geography_writer(oriented = oriented,  : 
  Loop 0 edge 314 crosses loop 5 edge 24

There seems no way to do this in a reasonable way, the MPA data is  too messy. It's quite frustrating.

**Comment by jeffreyhanson** [comment]
Hmm, do you know which country is causing the error? 

Also, you could try repairing the geometries again before dissolving it. E.g., something like this:

```
# load packages
library(wdpar)
library(sf)
library(dplyr)

# dissolve by country
result <-
  x %>%
  split(.$COUNTRY) %>% 
  lapply(function(y) {
    n <- y$COUNTRY[[1]]
   print(paste("starting", n))
    y <- sf::st_set_precision(y, 1e5)
    y <- sf::st_make_valid(y)
    y <- wdpa_dissolve(y)
    y$COUNTRY <- n
    y
  }) %>% 
  bind_rows()
```

Also, if you have access to ArcGIS, you cold try using the repair geometry tool and then the dissolve tool? IME ArcGIS is better at handling these geometry issues.

**Comment by fabeit** [comment]
That's a good idea to debugging the problem. It seems that it gets stuck at Australia.

**Comment by jeffreyhanson** [comment]
Hmm, could you try increasing the precision in the above coded to something super high like `1e10`?

Also, just to check, are you using the latest version of the sf and lwgeom packages?

Yeah, the license for the WDPA prohibits redistributing the database and any derived datasets (see https://www.protectedplanet.net/en/legal), which means people can't directly share any cleaned up or pre-processed versions of the dataset.

**Comment by jeffreyhanson** [comment]
Just to follow up @fabeit, were you able to resolve this issue? Anything I can do to help?

**Comment by fabeit** [comment]
I was never able to resolve the issue. I ended up asking UNEP to send me a shapefile with dissolved polygons for each country. I think something like this should be made public.

**Comment by jeffreyhanson** [comment]
Ah - sorry, I wasn't able to help with resolving it. Glad to hear that you got the data you needed in the end.
