### ISSUE TITLE
Error downloading "global" data with wdpa_fetch

### ISSUE THREAD

**Issue by jaseeverett** [prioritizr/wdpar#79]
Hi @jeffreyhanson 

Trying to download all the wdpa data with the "global" option and I get an error. Are you getting the same error?

I get the error whether I specific the `download_dir` or not.

``` r
wdpa_data <- wdpar::wdpa_fetch("global", wait = TRUE,
             download_dir = rappdirs::user_data_dir("wdpar"))
#> Warning in utils::unzip(x, exdir = tdir): error -1 in extracting from zip file
#> Error in wdpa_read(file_path, n): global data format not recognized.
```

<sup>Created on 2024-05-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jeffreyhanson** [comment]
Hi @jaseeverett,

Thank you very much for reporting this! I'll look into it and try and get back to you later today.

**Comment by jeffreyhanson** [comment]
Hmm, it seems to work on my computer (Ubuntu). I assume this on your M1 Mac? Internally, wdpar uses the curl package to handle downloads - could you try updating that and see if it works? If not, we could try and debug this togeather over zoom/teams?

**Comment by jeffreyhanson** [comment]
Also, it might be possible that there was previously an issue when downloading the global dataset  into the `rappdirs::user_data_dir("wdpar")` folder, so it's now failing when trying to import this cached data. So, maybe try deleting the glboal wdpar dataset from this folder and try running it again (so as to force wdpar to download the dataset again from Protected Planet)?

**Comment by jaseeverett** [comment]
Thanks @jeffreyhanson . No there isn't an issue with the cache. I tried it with new cache names, and also no cache and get the same issue. 
I just spoke to my student who reported it and he is using a 2018 MB Air. So possible a Mac issue, but not specific to the new Macs.

**Comment by jaseeverett** [comment]
I'll have a look at debugging it myself and get back to you. Stand by

**Comment by jeffreyhanson** [comment]
Just to follow up, were you able to debug the issue?

**Comment by jaseeverett** [comment]
Hey @jeffreyhanson . Yes I think I have but I'm just getting a student to test it on their computer to see if it works for them. Will get back to you shortly.

**Comment by jaseeverett** [comment]
#81 should solve this
